### ISSUE TITLE
ability to use this boilerplate w/o gateway connection

### ISSUE THREAD

**Issue by zwinnerman-fleetdm** [Serpentiel/arikawa-boilerplate#9]
**What is currently missing?**

As part of me using this boilerplate in an AWS Lambda, we can't maintain a gateway connection. Because of this, we should be able to use this without a gateway connection.

**How could this be improved?**

**Is this a feature you would work on yourself?**

- [ ] I plan to open a pull request for this feature.

**Comment by Serpentiel** [comment]
hey, @zwinnerman-fleetdm! 👋

thanks for raising this!

I'm going to prepare a PR that provides a convenient way to use gateway-less state in the boilerplate
